### ISSUE TITLE
SvgContainer example works only in Chromium, fails in FireFox

### ISSUE THREAD

**Issue by vobloeb** [raquo/laminar-examples#10]
FireFox 112 on Linux, Laminar 15.0.1, ScalaJS 1.13.2, Scala 2.13.11:

![Screenshot_2023-07-02_19-07-59](https://github.com/raquo/laminar-examples/assets/76634406/20032edd-491f-4cc0-b511-43f69623cb51)

**Comment by raquo** [comment]
Thanks for the report, reproduced. You can avoid the problem for now by removing the `xmlns := "..."` as it's usually not needed for inline SVGs, and it's the `xmlns` attribute that's broken. More details here: https://github.com/raquo/Laminar/issues/143

**Comment by raquo** [comment]
Fixed in Laminar 16.0.0, which will be released next week.
