### ISSUE TITLE
Ajax example is not working

### ISSUE THREAD

**Issue by tonicsystems** [raquo/laminar-examples#8]
I get this error on `https://laminar.dev/examples/ajax`

```
Starting: GET http://api.zippopotam.us/us/90210
Ready state: 1
Ready state: 4
Ajax request failed: unknown network reason.

```

**Comment by tonicsystems** [comment]
I think may be I was being slightly daft raising this issue. 
The examples are meant to be run on your own local environment by following the steps in the readme.

**Comment by raquo** [comment]
@tonicsystems No you were right, these examples are supposed to work on laminar.dev just as well.

It didn't work there because I was sending requests to `http` urls from an `https` origin. Weird that it worked before. I've just fixed it.
